server:
  port: 1111


# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adv_guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    db-name: adv_guns #用来搜集数据库的所有表
    filters: wall,mergeStat.mysql.jdbc.Driver